name: feroza
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  barcode_scan: ^3.0.1
  carousel_slider: ^2.2.1
  photo_view: ^0.9.2
  dio: ^3.0.9
  freezed_annotation: ^0.7.1
  dartz: ^0.9.1
  get_it: ^4.0.2
  injectable: ^1.0.4
  bloc: ^6.0.2
  flutter_bloc: ^6.0.1
  provider: ^4.3.2
  share: ^0.6.4+3
  image_downloader: ^0.20.0
  material_design_icons_flutter: ^4.0.5345
  cached_network_image: ^2.2.0+1
  rename: ^1.2.0
  url_launcher: ^5.5.0
  firebase_ml_vision: ^0.9.4
  image_picker: ^0.6.7+2
  firebase_core: ^0.4.0+9
  auto_size_text: ^2.1.0
  flappy_search_bar: ^1.7.2
  get: ^3.4.6
  shared_preferences: ^0.5.8
  imei_plugin: ^1.2.0
  flutter_money_formatter: ^0.8.3
  # geolocator: ^5.3.2+2
  pull_to_refresh: ^1.6.1
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.10.9
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5
  injectable_generator: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/
    - assets/images/
    - assets/



